using UnityEngine;
//UNA INTERFACE ES UNA PLANTILLA QUE PUEDO USAR PARA QUE TODOS LOS SCRIPTS QUE LA IMPLEMENTAN TENGAN LAS MISMAS FUNCIONES
//ESO ME ASEGURA QUE PUEDA LLAMAR A LA MISMA FUNCION AUNQUE LOS COMPONENTES SEAN DE TIPO DIFERENTE

public interface IInteractable
{
    void Interact();

}
